### ISSUE TITLE
Make the import branch main

### ISSUE THREAD

**Issue by keir** [JoshLee0915/GodotLDtkImporter#16]
The importer branch is already semi-working. I suggest pushing that branch as main with the README mentioning that this isn't quite ready for prime time.

Thanks for starting this project!

**Comment by JoshLee0915** [comment]
Thank you, and a valid point. I have not merged it quite yet as I have not had the time to really fully test it yet but I should release at least an alpha since I have the actual resource plugin done. Ill work start a release branch here and get a readme setup and even shove that onto the asset lib.

**Comment by JoshLee0915** [comment]
Ok, a prerelease of the importer has been made. You can find it here:
https://github.com/JoshLee0915/GodotLDtkImporter/releases

Also, submitted to the asset library and awaiting approval.
